/*Package cmd functions for create user commands.
Copyright © 2020 Elric Hindy <anunstableunicorn@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
package cmd

import (
	"errors"
	"fmt"
	"log"
	"strings"

	"github.com/unstableunicorn/cogo/lib"

	cognito "github.com/aws/aws-sdk-go/service/cognitoidentityprovider"
	"github.com/spf13/cobra"
)

var clientMetadata []string
var deliveryMedium []string
var userAttributes []string
var tempPassword string

var suppress bool
var updateUserIfExists bool
var generatePasswordFlag bool

// createUserCmd represents the user command
var createUserCmd = &cobra.Command{
	Use:   "user",
	Short: "Create an AWS Cognito user",
	Long: `Create an AWS Cognito user.

  Examples: 
  Basic use, create a user named ''
  >cogo -p <poolid> create user mynewusername

  Create a user with description and precedence
  >cogo -p <poolid> create user User.Name -d "A user that does user things" --precedence 3 
  .`,
	Aliases: userAliases,
	Args: func(cmd *cobra.Command, args []string) error {
		return checkUserArgs(cmd, args)
	},
	Run: func(cmd *cobra.Command, args []string) {
		userInput := createCreateUsersInput(args[0])
		createUser(userInput)
	},
}

func init() {
	createCmd.AddCommand(createUserCmd)

	createUserCmd.Flags().StringSliceVar(&clientMetadata, "clientmetadata", []string{}, "Comma separated list of client metadata e.g Key=Value[,Key2=Value2]")
	createUserCmd.Flags().StringSliceVar(&deliveryMedium, "delivery", []string{}, "List of desired delivery mediums, must be 'EMAIL' and/or 'SMS'")
	createUserCmd.Flags().BoolVar(&suppress, "suppress", false, "If set the user will NOT be send an email, default will send an email")
	createUserCmd.Flags().StringVar(&tempPassword, "password", "", "Password to set for the user, autogenerated if not provided, (Minimum Length: 6)")
	createUserCmd.Flags().StringSliceVar(&userAttributes, "attributes", []string{}, `Comma separated list of user attributes e.g Key=Value[,Key2=Value2]
 This is where the email is set. See usage`)

	createUserCmd.Flags().BoolVarP(&updateUserIfExists, "update", "u", false, "If the user exists this will update the user")
	createUserCmd.Flags().BoolVar(&generatePasswordFlag, "autopassword", false, "Auto generate a password for the user")
}

func checkUserArgs(cmd *cobra.Command, args []string) error {
	if len(args) != 1 {
		s := fmt.Sprintf("An single value is required for the user name, provided values: '%v'", args)
		return errors.New(s)
	}

	if len(tempPassword) > 0 {
		if len(tempPassword) < 6 {
			return errors.New("Password does not meet minimum length")
		}
	} else {
		if generatePasswordFlag {
			pass, err := lib.GeneratePassword(12, 3, 3, 3)
			if err != nil {
				return err
			}
			tempPassword = pass
		} else {
			return errors.New("Password must be set or use --autopassword")
		}
	}

	if len(deliveryMedium) > 0 {
		for _, v := range deliveryMedium {
			if v != cognito.DeliveryMediumTypeEmail && v != cognito.DeliveryMediumTypeSms {
				return errors.New("Delivery medium must be EMAIL and or SMS")
			}
		}
	}

	return nil
}

func createCreateUsersInput(userName string) *cognito.AdminCreateUserInput {
	// Generate the mapped attributes
	mappedClientMetadata := make(map[string]*string)
	if len(clientMetadata) > 0 {
		for _, a := range clientMetadata {
			values := strings.Split(a, "=")
			if len(values) != 2 {
				errorString := fmt.Sprintf("Invalid client metadata %v \n", a)
				log.Fatal(errorString)
			}
			mappedClientMetadata[values[0]] = &values[1]
		}
	}

	createUsersInput := &cognito.AdminCreateUserInput{
		UserPoolId: &poolID,
		Username:   &userName,
	}

	if len(mappedClientMetadata) > 0 {
		createUsersInput.ClientMetadata = mappedClientMetadata
	}

	if len(deliveryMedium) > 0 {
		var dm []*string
		for _, v := range deliveryMedium {
			dm = append(dm, &v)
		}
		createUsersInput.DesiredDeliveryMediums = dm
	}

	if updateUserIfExists {
		action := cognito.MessageActionTypeResend
		if suppress {
			action = cognito.MessageActionTypeSuppress
		}
		createUsersInput.MessageAction = &action
	}

	var mappedUserAttributes []*cognito.AttributeType
	if len(userAttributes) > 0 {
		for _, a := range userAttributes {
			values := strings.Split(a, "=")
			if len(values) != 2 {
				errorString := fmt.Sprintf("Invalid user attributes %v \n", a)
				log.Fatal(errorString)
			}
			attrib := cognito.AttributeType{
				Name:  &values[0],
				Value: &values[1],
			}
			mappedUserAttributes = append(mappedUserAttributes, &attrib)
		}
		createUsersInput.UserAttributes = mappedUserAttributes
	}

	return createUsersInput
}

func createUser(userInput *cognito.AdminCreateUserInput) {
	user, err := cognitoSvc.AdminCreateUser(userInput)

	if err != nil {
		// try and update the user
		if updateUserIfExists {
			fmt.Println("Need to handle updating a user")
		} else {
			lib.HandleAWSError("creating user", err, true)
		}
	} else {
		fmt.Println(user.GoString())
	}
}
