name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Get Modules
      run: make getmodules

    - name: Build Static
      run: make static

    - name: Test
      run: make test
    
    - name: Build All
      run: make build

    - name: Upload linux
      uses: actions/upload-artifact@v1
      with:
        name: linux-bin
        path: bin/cogo-linux*
    - name: Upload darwin
      uses: actions/upload-artifact@v1
      with:
        name: darwin-bin
        path: bin/cogo-darwin*
    - name: Upload windows
      uses: actions/upload-artifact@v1
      with:
        name: windows-bin
        path: bin/cogo-windows*
